all_interchangeables = {
    "sports": ["basketball", "soccer", "baseball", "football"],
    "something": ["something", "anything"],
    "animal": [
        "bear",
        "tiger",
        "ant",
        "rat",
        "bird",
        "lion",
        "wolf",
        "turtle",
        "panda",
    ],
    "pet": ["dog", "cat", "monkey", "kitten", "puppy", "mouse", "hamster"],
    "instrument": [
        "guitar",
        "piano",
        "violin",
        "flute",
        "saxophone",
        "harmonica",
        "banjo",
        "drum",
        "harp",
    ],
    "planet": [
        "Mercury",
        "Mars",
        "Venus",
        "Neptune",
        "Jupiter",
        "Saturn",
        "Earth",
        "Uranus",
    ],
    "president": [
        "Trump",
        "Obama",
        "Bush",
        "Clinton",
        "Reagan",
        "Carter",
        "Nixon",
        "Lincoln",
        "Washington",
    ],
    "country": [
        "Slovenia",
        "iceland",
        "America",
        "United States",
        "Mexico",
        "Canada",
        "Peru",
        "Ecuador",
        "Germany",
        "France",
        "England",
        "Chad",
        "South Africa",
        "Niger",
        "Nigeria",
        "China",
        "Japan",
        "India",
        "Malaysia",
    ],
    "male_names": [
        "Bob",
        "John",
        "Sam",
        "Michael",
        "Bill",
        "Fred",
        "Harry",
        "Justin",
        "Vincent",
        "Sen",
        "Jian",
        "Braden",
        "Chad",
        "Jake",
        "Christopher",
        "Steven",
        "Stephen",
        "Mark",
    ],
    "each": ["each", "every"],
    "female_names": [
        "Mary",
        "Sally",
        "Sue",
        "Clara",
        "Sarah",
        "Sara",
        "Ines",
        "Emily",
        "Violet",
        "Elizabeth",
        "Elise",
        "Julia",
        "Sonali",
        "Isabel",
        "Hilary",
        "Jennifer",
        "Anna",
    ],
    "entertainment": ["movie", "film", "drama", "musical", "opera"],
    "languages": [
        "English",
        "French",
        "Spanish",
        "German",
        "Chinese",
        "Italian",
        "Arabic",
        "Japanese",
        "Russian",
    ],
    "food": [
        "pasta",
        "cabbage",
        "onion",
        "apple",
        "tomato",
        "cucumber",
        "pear",
        "fish",
    ],
    "journey": ["journey", "adventure"],
    "wonderful": [
        "fantastic",
        "wonderful",
        "fun",
        "charming",
        "delightful",
        "glorious",
        "pleasurable",
    ],
    "bad": ["bad", "in-your-face", "boring"],
    "speed": ["quick", "fast", "at lightening speed", "warp speed", "rapid", "speedy"],
    "slow": ["foot-dragging", "slow", "snails-pace"],
    "folks": ["people", "men", "women", "folks"],
    "youngens": ["boys", "girls", "kids", "children"],
    "person": [
        "person",
        "man",
        "woman",
        "servant",
        "manager",
        "employee",
        "sailor",
        "mother",
        "father",
        "teacher",
        "doctor",
        "dentist",
        "grandparent",
        "grandma",
        "grandpa",
    ],
    "juvenile": ["girl", "child", "boy"],
    "baby": ["baby", "toddler", "infant", "little boy", "little girl", "youngest one"],
    "plot": ["story", "plot", "tale"],
    "sad": ["heartbreaking", "heart-wrenching", "emotional", "glum", "sad"],
    "interesting": ["intriguing", "interesting", "fascinating"],
    "intentional": ["intentional", "carefully placed", "thoughtfully chosen"],
    "dead - center": ["right on", "perfect", "just right", "dead-center"],
    "desperate": ["desperate", "too eager"],
    "fool": ["moron", "idiot", "dunce", "fool"],
    "burning": ["burning", "charring", "smoking"],
    "cutting": ["cutting", "slicing", "chopping", "stabbing", "dicing"],
    "units": ["billion", "hundred", "million", "thousand"],
    # "one" : ["one", "a"],
}

change_meaning = {
    "nums": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
    ],  # do not change meaning for QNLI if question is when
    "numbers": [
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
        "twenty",
        "thirty",
        "forty",
        "fifty",
        "sixty",
        "seventy",
        "eighty",
        "ninety",
    ],
    "units": ["billion", "hundred", "million", "thousand", "percent"],
    "first": [
        "first",
        "second",
        "third",
        "fourth",
        "fifth",
        "sixth",
        "seventh",
        "eighth",
        "ninth",
        "tenth",
        "eleventh",
        "twelfth",
        "thirteenth",
        "fourteenth",
        "fifteenth",
        "sixteenth",
        "seventeenth",
        "eighteenth",
        "nineteenth",
        "twentieth",
        "thirteith",
        "fortieth",
        "fiftieth",
        "sixtieth",
    ],
    "time": ["month", "day", "year", "second", "hour"],
    "tall": ["tall", "short"],
    "heavy": ["heavy", "light"],
    "big": ["big", "small"],
}
