# launches single task or multitask models of MetalModel with favorable GLUE parameters
python launch.py \
    --device 0 \
    --bert_model bert-base-uncased \
    --max_len 200 \
    --warmup_unit "epochs" \
    --lr_scheduler "linear" \
    --min_lr 0 \
    --log_every 0.25 --score_every 0.25 \
    --checkpoint_dir checkpoints \
    --checkpoint_metric model/valid/gold/glue_score \
    --checkpoint_metric_mode max \
    --checkpoint_best True \
    --progress_bar 1 \
    --lr 5e-3 \
    --l2 0 \
    --batch_size 32 \
    --tasks SST2 \
    --split_prop None \
    --n_epochs 10 \
    --max_datapoints -1 \
    --reinit_bert True \
