temporal = ["before", "after", "past"]
possessive = ["inside", "within", "with"]
comparatives = [
    "more",
    "less",
    "bigger",
    "smaller",
    "better",
    "worse",
    "shorter",
    "taller",
    "most",
    "least",
    "than",
]
negations = [
    "no",
    "not",
    "none",
    "nobody",
    "nothing",
    "neither",
    "nowhere",
    "never",
    "hardly",
    "scarcely",
    "barely",
    "doesn’t",
    "isn’t",
    "wasn’t",
    "shouldn’t",
    "wouldn’t",
    "couldn’t",
    "won’t",
    "can’t",
    "don’t",
]
qwords = [
    "who",
    "what",
    "where",
    "when",
    "why",
    "how",
    "will",
    "do",
    "does",
    "if",
    "which",
    "should",
    "could",
    "can",
]
wh_words = ["who", "what", "where", "when", "why", "which", "how"]
